name = "PsychometricTests"
uuid = "f849c049-6981-48c9-9be9-354155c91302"
authors = ["Philipp Gewessler"]
version = "0.1.0"

[deps]
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
